### ISSUE TITLE
Migrate WCF Services - Not Found

### ISSUE THREAD

**Issue by GeorgeSchiro** [CodeFactoryLLC/WCF-To-gRPC#6]
From [How It Works](https://github.com/CodeFactoryLLC/WCF-To-gRPC#how-it-works):

"After compiling and running the automation template, load up any WCF solution and add a new gRPC project to the solution. Right click on the gRPC project from the solution explorer and select Migrate WCF Services."

I was able to compile the "WCF-To-gRPC" solution - but only after removing this from the "WcfToGrpcCommands.csproj" project file:

    <Target Name="AfterBuild">
      <Exec Command="&quot;$(DevEnvDir)PublicAssemblies\CodeFactory\Packager\cfxpackager.exe&quot; &quot;$(TargetPath)&quot;" />
      
    </Target>

Sadly, while the "WCF-To-gRPC" solution compiles now (and launches a new VS IDE instance), I do not see a "Migrate WCF Services" context menu item after adding a new "ASP.NET Core gRPC Service" to my existing WCF solution (loaded in the new VS IDE instance).

What am I missing?

Any help would be appreciated. Thanks!

**Comment by bfencken** [comment]
Hi George, The runtime was updated since this automation was released. Will let you know as soon as we have it updated to run on the current CF runtime. Thanks for the note. CC: @sgiffinlcd

**Comment by GeorgeSchiro** [comment]
Thanks Bill, but please correct me if I am mistaken. The real issue is that a dependency (ie "the runtime") was never actually included in this repo, right? And that dependency (ie. the particular version) is no longer available, is that correct?

Do you have any sense for when this tool might be rendered usable? I was hoping to make some progress with it over the coming week.

**Comment by bfencken** [comment]
Correct, the current CF run time is not compatible with that particular automation command.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GeorgeSchiro** [comment]
So I have no hope of using this tool anytime soon. Does that pretty much sum up the situation Bill?

**Comment by bfencken** [comment]
In hindsight, we should probably flag some of these older automation packages to indicate which version of the code factory runtime they are/were compatible with. We're going to archive this one for now and hopefully we can get a refreshed version of it pushed out within the next month or so.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GeorgeSchiro** [comment]
That sounds like a good idea Bill.

It's also a good idea to publish repositories that include all dependencies and which are also actually usable and productive to folks spending their limited time and attention on them. Just sayin'. ;o)
